import { mkdirSync, mkdtempSync, rmSync, writeFileSync } from "node:fs"
import { tmpdir } from "node:os"
import path from "node:path"
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest"
import {
  SUPPRESSION_EXCEPTION_SCHEMA,
  deriveSuppressionId,
  summarizeByDomain,
  suppressions,
  whyUnacceptable,
} from "../checks/suppressions.js"
import { validateExceptionRegistry } from "../checks/exception-record.js"
import type { Suppression } from "../scripts/suppressions-scan.mjs"
import { COMPLETE_V2, makeContext, makeJsonResult, makeResult } from "./support.js"

const make = (over: Partial<Suppression> = {}): Suppression => ({
  id: "suppression:eslint:no-console:src/a.ts:0123456789ab",
  domain: "eslint",
  rule: "no-console",
  directive: "eslint-disable-next-line",
  file: "src/a.ts",
  line: 3,
  reason: "the CLI prints to the terminal",
  blockReason: "",
  blanket: false,
  documented: true,
  closing: false,
  ...over,
})

let cwd: string
beforeEach(() => {
  cwd = mkdtempSync(path.join(tmpdir(), "ipc-suppressions-check-"))
  vi.spyOn(process, "cwd").mockReturnValue(cwd)
})
afterEach(() => {
  vi.restoreAllMocks()
  rmSync(cwd, { recursive: true, force: true })
})

const report = (found: Suppression[], files = 12) =>
  makeJsonResult({ ok: true, files, suppressions: found })
const run = (result: ReturnType<typeof makeJsonResult>) =>
  suppressions().policy(makeContext(result))
function writeRegistry(records: readonly unknown[]): void {
  mkdirSync(path.join(cwd, ".repo-contract/exceptions"), { recursive: true })
  writeFileSync(
    path.join(cwd, ".repo-contract/exceptions/suppressions.json"),
    JSON.stringify({ exceptions: records }),
  )
}
const record = (s: Suppression, over: Record<string, unknown> = {}) => ({
  id: s.id,
  version: 2,
  justification: "Generated by ts-json-schema-generator.",
  domain: s.domain,
  rule: s.rule,
  file: s.file,
  anchor: s.id.split(":").at(-1),
  ...COMPLETE_V2,
  ...over,
})

describe("whyUnacceptable()", () => {
  it("accepts a documented suppression and any closing directive", () => {
    expect(whyUnacceptable(make())).toBeUndefined()
    expect(
      whyUnacceptable(make({ closing: true, documented: false, blanket: true })),
    ).toBeUndefined()
  })

  it("rejects a blanket one before an undocumented one", () => {
    expect(whyUnacceptable(make({ blanket: true, documented: false }))).toContain("blanket")
    expect(whyUnacceptable(make({ blanket: true }))).toContain("blanket")
    expect(whyUnacceptable(make({ documented: false }))).toBe("no reason given")
  })
})

describe("summarizeByDomain()", () => {
  it("counts opening suppressions per tool, most first, ignoring closing ones", () => {
    expect(
      summarizeByDomain([
        make(),
        make({ domain: "stryker" }),
        make({ domain: "stryker" }),
        make({ domain: "stryker", closing: true }),
        make({ domain: "coverage" }),
      ]),
    ).toBe("stryker 2, coverage 1, eslint 1")
    expect(summarizeByDomain([])).toBe("")
  })
})

describe("suppressions() policy", () => {
  it("runs the bundled scanner", () => {
    const check = suppressions()
    expect((check.run as readonly string[])[0]).toBe("node")
    expect(path.basename((check.run as readonly string[])[1] as string)).toBe(
      "check-suppressions.mjs",
    )
  })

  it("passes, counting them by tool, when every suppression gives its reason", async () => {
    const result = await run(report([make(), make({ domain: "stryker" }), make({ closing: true })]))
    expect(result).toEqual({
      outcome: "pass",
      rationale: "Suppressions: 2 in 12 file(s) (eslint 1, stryker 1), every one gives its reason.",
    })
  })

  it("passes, saying so, when there are none", async () => {
    expect(await run(report([], 5))).toEqual({
      outcome: "pass",
      rationale: "Suppressions: none in 5 file(s).",
    })
  })

  it("fails, naming file, line, tool, rule and the id to record, for one with no reason", async () => {
    const result = await run(report([make({ documented: false })]))
    expect(result.outcome).toBe("fail")
    expect(result.rationale).toContain("1 problem(s)")
    expect(result.rationale).toContain(
      "- src/a.ts:3 eslint-disable-next-line no-console: no reason given -- id suppression:eslint:no-console:src/a.ts:0123456789ab",
    )
  })

  it("fails a blanket suppression even though it gives a reason, and omits the rule when it names none", async () => {
    const result = await run(
      report([
        make({
          blanket: true,
          rule: "*",
          directive: "eslint-disable",
          id: "suppression:eslint:*:src/a.ts:aaaaaaaaaaaa",
        }),
      ]),
    )
    expect(result.outcome).toBe("fail")
    expect(result.rationale).toContain("src/a.ts:3 eslint-disable: blanket")
  })

  it("lists at most twenty and counts the rest", async () => {
    const many = Array.from({ length: 22 }, (_, i) =>
      make({ documented: false, id: `suppression:eslint:r:f:${String(i).padStart(12, "0")}` }),
    )
    const result = await run(report(many))
    expect(result.rationale).toContain("22 problem(s)")
    expect(result.rationale).toContain("...and 2 more.")
  })

  it("accepts a complete record for a suppression that cannot carry a reason, and says so", async () => {
    const bad = make({
      documented: false,
      blanket: true,
      rule: "*",
      directive: "eslint-disable",
      id: "suppression:eslint:*:src/gen.ts:0123456789ab",
      file: "src/gen.ts",
    })
    writeRegistry([record(bad)])
    const result = await run(report([bad]))
    expect(result.outcome).toBe("pass")
    expect(result.rationale).toContain(
      "or has a record in .repo-contract/exceptions/suppressions.json",
    )
  })

  it("fails a record that is incomplete or expired, naming what is missing", async () => {
    const bad = make({ documented: false })
    writeRegistry([record(bad, { residualRisk: "" })])
    expect((await run(report([bad]))).rationale).toContain(
      "its record is incomplete (missing: residualRisk)",
    )
    writeRegistry([record(bad, { expires: "2020-01-01" })])
    expect((await run(report([bad]))).rationale).toContain("expires (2020-01-01 has passed)")
  })

  it("fails a stale record: the suppression is gone, or now gives its reason", async () => {
    const gone = make({
      id: "suppression:eslint:no-console:src/old.ts:ffffffffffff",
      file: "src/old.ts",
    })
    writeRegistry([record(gone)])
    const result = await run(report([make()]))
    expect(result.outcome).toBe("fail")
    expect(result.rationale).toContain(
      `Stale record in .repo-contract/exceptions/suppressions.json: "${gone.id}"`,
    )
  })

  it("fails when the registry is malformed", async () => {
    writeRegistry([{ id: "nope" }])
    const result = await run(report([make()]))
    expect(result.outcome).toBe("fail")
    expect(result.rationale).toContain("suppressions.json failed to load")
  })

  it("fails when the scan itself failed, or its output is not the envelope", async () => {
    expect((await run(makeJsonResult({ ok: false, error: "boom" }))).rationale).toBe(
      "Suppressions: could not scan the repository: boom",
    )
    expect((await run(makeResult({ status: "timed_out" }))).outcome).toBe("fail")
  })
})

describe("SUPPRESSION_EXCEPTION_SCHEMA", () => {
  const parts = { domain: "eslint", rule: "no-console", file: "src/a.ts", anchor: "0123456789ab" }
  const rec = (over: Record<string, unknown> = {}) => ({
    id: deriveSuppressionId(parts),
    version: 1,
    justification: "j",
    ...parts,
    ...over,
  })
  const validate = (entry: unknown) =>
    validateExceptionRegistry([entry], SUPPRESSION_EXCEPTION_SCHEMA)

  it("derives the id from domain, rule, file and anchor", () => {
    expect(deriveSuppressionId(parts)).toBe("suppression:eslint:no-console:src/a.ts:0123456789ab")
  })

  it("accepts a well-formed record and rejects a missing field or a mismatched id", () => {
    expect(validate(rec()).ok).toBe(true)
    for (const field of ["domain", "rule", "file", "anchor"]) {
      const result = validate(rec({ [field]: "" }))
      expect(result.ok).toBe(false)
      if (!result.ok)
        expect(result.errors).toEqual([`exceptions[0].${field} must be a non-empty string.`])
    }
    const mismatch = validate(rec({ anchor: "ffffffffffff" }))
    expect(mismatch.ok).toBe(false)
    if (!mismatch.ok) expect(mismatch.errors[0]).toContain("does not match the id derived")
  })
})
