/**
 * Every place a source file tells a tool to stop enforcing a rule -- `eslint-disable`, `@ts-expect-error`,
 * `// Stryker disable`, a `v8 ignore` comment, `jscpd:ignore-start`, `prettier-ignore`, `markdownlint-disable`,
 * `secretlint-disable` -- is an exception to the standard written as a comment. A comment is the
 * weakest place for one: nothing reads it back, nothing notices when it stops being true, and nothing
 * counts them. This check reads them all back (`scripts/suppressions-scan.mjs` finds them by parsing
 * the code, so a string that merely mentions `eslint-disable` is not one), and the complete list is
 * kept verbatim in the contract's evidence on every run.
 *
 * ## Policy
 *
 * A suppression must **say why**. The reason is written where the suppression is:
 *
 * ```ts
 * // eslint-disable-next-line @typescript-eslint/no-explicit-any -- suites are user-shaped data; typing each figure only forces casts on callers.
 * // Stryker disable next-line StringLiteral: an equivalent mutant -- readFile(path, "") yields a Buffer JSON.parse decodes identically.
 * // @ts-expect-error the fixture is deliberately the wrong shape to exercise the guard.
 * // v8 ignore comments take the same form: `v8 ignore next -- <why>`.
 * ```
 *
 * A reason is at least {@link MIN_REASON_LENGTH} characters on the directive itself, or -- for the
 * directives that cannot carry one (a `// Stryker disable` whose explanation runs on above it) -- the
 * comment block directly above it, at least {@link MIN_BLOCK_REASON_LENGTH} characters.
 *
 * A **blanket** suppression -- one that names no rule (`eslint-disable` alone), `@ts-ignore` (which goes
 * quiet by itself) or `@ts-nocheck` (a whole file) -- is never accepted by a reason alone.
 *
 * Anything that fails either test needs a complete record in
 * `.repo-contract/exceptions/suppressions.json`, the same registry model every other exception uses (see
 * EXCEPTIONS.md): for the rare suppression that cannot carry its own reason, such as a generated or
 * vendored file. A record whose suppression is gone, or has since been given a reason, is stale and
 * fails until deleted. The record id is anchored to the directive and the code it covers, not to a line
 * number, so an edit elsewhere in the file leaves it alone:
 *
 * ```json
 * {
 *   "exceptions": [
 *     {
 *       "id": "suppression:eslint:*:src/generated/schema.ts:0123456789ab",
 *       "version": 2,
 *       "justification": "Generated by ts-json-schema-generator; regenerated on every build.",
 *       "domain": "eslint",
 *       "rule": "*",
 *       "file": "src/generated/schema.ts",
 *       "anchor": "0123456789ab",
 *       "ruleBroken": "Every ESLint suppression names its rule and says why.",
 *       "attempted": "Configuring the generator to emit named, described disables.",
 *       "constraint": "The generator writes a fixed header comment; there is no option for it.",
 *       "whyPreferable": "An ignore entry for the file is a second place to keep in sync, and loses this record's review.",
 *       "residualRisk": "None for the shipped package; the file is overwritten on every build.",
 *       "revisitWhen": "The generator supports a configurable header, or the file stops being generated.",
 *       "expires": ""
 *     }
 *   ]
 * }
 * ```
 */
import path from "node:path"
import type { CheckDefinitionConfig, PolicyResult } from "repo-contract"
import type { ExceptionRecordCore, StandardSchemaV1 } from "repo-contract/helpers"
import { loadExceptionRegistry } from "repo-contract/helpers"
import type { Suppression } from "../scripts/suppressions-scan.mjs"
import { MIN_BLOCK_REASON_LENGTH, MIN_REASON_LENGTH } from "../scripts/suppressions-scan.mjs"
import { incompleteFields } from "./environment-exceptions.js"
import { isValidNonEmptyStringField, validateExceptionRegistry } from "./exception-record.js"
import type { ExceptionRegistrySchema, ExceptionV2Fields } from "./exception-record.js"
import { packageRoot, parseToolEnvelope } from "./shared.js"

export { MIN_BLOCK_REASON_LENGTH, MIN_REASON_LENGTH }

const REGISTRY_RELATIVE_PATH = ".repo-contract/exceptions/suppressions.json"
const scriptPath = path.join(packageRoot, "scripts", "check-suppressions.mjs")
const MAX_LISTED = 20

/** One `.repo-contract/exceptions/suppressions.json` record. */
export interface SuppressionExceptionRecord extends Partial<ExceptionV2Fields> {
  readonly id: string
  readonly version: 1 | 2
  readonly justification: string
  readonly domain: string
  readonly rule: string
  readonly file: string
  readonly anchor: string
}

/**
 * `suppression:<domain>:<rule>:<file>:<anchor>`.
 * @param parts - the identity fields.
 * @returns the id a record for this suppression must carry.
 * @internal Exported for direct unit coverage.
 */
export function deriveSuppressionId(parts: {
  readonly domain: string
  readonly rule: string
  readonly file: string
  readonly anchor: string
}): string {
  return `suppression:${parts.domain}:${parts.rule}:${parts.file}:${parts.anchor}`
}

/** @internal Exported for direct unit coverage. */
export const SUPPRESSION_EXCEPTION_SCHEMA: ExceptionRegistrySchema<SuppressionExceptionRecord> = {
  namespace: "suppression:",
  metadataKeys: ["domain", "rule", "file", "anchor"],
  validateRecord(core: ExceptionRecordCore, raw, index, errors) {
    const at = `exceptions[${String(index)}]`
    const { domain, rule, file, anchor } = raw
    const domainValid = isValidNonEmptyStringField(domain, `${at}.domain`, errors)
    const ruleValid = isValidNonEmptyStringField(rule, `${at}.rule`, errors)
    const fileValid = isValidNonEmptyStringField(file, `${at}.file`, errors)
    const anchorValid = isValidNonEmptyStringField(anchor, `${at}.anchor`, errors)
    if (!domainValid || !ruleValid || !fileValid || !anchorValid) return undefined
    const identity = { domain, rule, file, anchor }
    const derived = deriveSuppressionId(identity)
    if (derived !== core.id) {
      errors.push(
        `${at}.id ${JSON.stringify(core.id)} does not match the id derived from its own domain/rule/file/anchor (${JSON.stringify(derived)}).`,
      )
      return undefined
    }
    return { id: core.id, version: 1, justification: core.justification, ...identity }
  },
}

const registrySchema: StandardSchemaV1<unknown, readonly SuppressionExceptionRecord[]> = {
  "~standard": {
    version: 1,
    vendor: "internal-package-contract",
    validate: (value: unknown) => {
      const result = validateExceptionRegistry(value, SUPPRESSION_EXCEPTION_SCHEMA)
      return result.ok
        ? { value: result.records }
        : { issues: result.errors.map((message) => ({ message })) }
    },
  },
}

type ToolResult =
  | { readonly ok: true; readonly files: number; readonly suppressions: readonly Suppression[] }
  | { readonly ok: false; readonly error: string }

/**
 * Why a suppression is not acceptable on its own, or `undefined` when it is.
 * @param suppression - one parsed suppression.
 * @returns a short reason, e.g. `"blanket"` or `"no reason given"`.
 * @internal Exported for direct unit coverage.
 */
export function whyUnacceptable(suppression: Suppression): string | undefined {
  if (suppression.closing) return undefined
  if (suppression.blanket)
    return "blanket (names no rule, or a form that never says what it excuses)"
  if (!suppression.documented) return "no reason given"
  return undefined
}

/**
 * Counts the opening suppressions per tool, as `eslint 2, stryker 42`.
 * @param suppressions - every suppression found.
 * @returns the summary, empty when there are none.
 * @internal Exported for direct unit coverage.
 */
export function summarizeByDomain(suppressions: readonly Suppression[]): string {
  const counts = new Map<string, number>()
  for (const suppression of suppressions) {
    if (suppression.closing) continue
    counts.set(suppression.domain, (counts.get(suppression.domain) ?? 0) + 1)
  }
  return [...counts.entries()]
    .sort((a, b) => b[1] - a[1] || a[0].localeCompare(b[0]))
    .map(([domain, count]) => `${domain} ${String(count)}`)
    .join(", ")
}

/** @returns the `Suppressions` check. */
export function suppressions(): CheckDefinitionConfig {
  return {
    run: ["node", scriptPath],
    output: { format: "json" },
    policy: async ({ result }): Promise<PolicyResult> => {
      const envelope = parseToolEnvelope<ToolResult>(result, "node", "Suppressions:")
      if (!envelope.ok) return envelope.result
      const report = envelope.value
      if (!report.ok) {
        return {
          outcome: "fail",
          rationale: `Suppressions: could not scan the repository: ${report.error}`,
        }
      }

      const loaded = await loadExceptionRegistry({
        path: path.join(process.cwd(), REGISTRY_RELATIVE_PATH),
        schema: registrySchema,
      })
      if (!loaded.ok) {
        return {
          outcome: "fail",
          rationale: [
            `Suppressions: ${REGISTRY_RELATIVE_PATH} failed to load:`,
            ...loaded.errors.map((error) => `- ${error}`),
          ].join("\n"),
        }
      }

      const now = new Date()
      const records = new Map(loaded.records.map((record) => [record.id, record]))
      const offenders: { suppression: Suppression; problem: string }[] = []
      const covered = new Set<string>()
      for (const suppression of report.suppressions) {
        const problem = whyUnacceptable(suppression)
        if (problem === undefined) continue
        const record = records.get(suppression.id)
        if (record === undefined) {
          offenders.push({ suppression, problem })
          continue
        }
        covered.add(record.id)
        const missing = incompleteFields(record, now)
        if (missing.length > 0) {
          offenders.push({
            suppression,
            problem: `${problem}; its record is incomplete (missing: ${missing.join(", ")})`,
          })
        }
      }
      const stale = loaded.records.filter((record) => !covered.has(record.id))

      if (offenders.length === 0 && stale.length === 0) {
        const opening = report.suppressions.filter((s) => !s.closing)
        return {
          outcome: "pass",
          rationale:
            opening.length === 0
              ? `Suppressions: none in ${String(report.files)} file(s).`
              : `Suppressions: ${String(opening.length)} in ${String(report.files)} file(s) (${summarizeByDomain(report.suppressions)}), every one gives its reason${loaded.records.length > 0 ? ` or has a record in ${REGISTRY_RELATIVE_PATH}` : ""}.`,
        }
      }

      const lines = [
        ...offenders
          .slice(0, MAX_LISTED)
          .map(
            ({ suppression, problem }) =>
              `- ${suppression.file}:${String(suppression.line)} ${suppression.directive}${suppression.rule === "*" ? "" : ` ${suppression.rule}`}: ${problem} -- id ${suppression.id}`,
          ),
        ...(offenders.length > MAX_LISTED
          ? [`...and ${String(offenders.length - MAX_LISTED)} more.`]
          : []),
        ...stale.map(
          (record) =>
            `- Stale record in ${REGISTRY_RELATIVE_PATH}: ${JSON.stringify(record.id)} -- that suppression is gone or now gives its reason; delete this entry.`,
        ),
      ]
      return {
        outcome: "fail",
        rationale: [
          `Suppressions: ${String(offenders.length + stale.length)} problem(s). Give each suppression a reason where it is written (\`-- why\`), or record it in ${REGISTRY_RELATIVE_PATH}:`,
          ...lines,
        ].join("\n"),
      }
    },
  }
}
